name: Build Binaries
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        target:
          - x86_64-unknown-linux-gnu  # Only for Ubuntu
          - x86_64-pc-windows-msvc    # Only for Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Install dependencies for Linux
        if: matrix.platform == 'ubuntu-latest'
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Install dependencies for Windows
        if: matrix.platform == 'windows-latest'
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build Executable
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: steamid-replacer-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/steamid-replacer${{ matrix.platform == 'windows-latest' && '.exe' || '' }}
