name: Build Binaries
on: [push, pull_request]

jobs:
  default:
    name: Default
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        toolchain: [nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      
      - name: Install Linux target & strip
        if: matrix.platform == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y binutils
      
      - name: Install Windows target
        if: matrix.platform == 'windows-latest'
        run: rustup target add x86_64-pc-windows-msvc
      
      - name: Cache Rust
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/
            target/
      
      - name: Build Linux (force strip)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          strip --strip-all --strip-unneeded target/x86_64-unknown-linux-gnu/release/steamid-replacer
      
      - name: Build Windows
        if: matrix.platform == 'windows-latest'
        run: cargo build --release --target x86_64-pc-windows-msvc
      
      - uses: actions/upload-artifact@v4
        with:
          name: steamid-replacer-${{ matrix.platform }}
          path: target/${{ matrix.platform == 'ubuntu-latest' && 'x86_64-unknown-linux-gnu' || 'x86_64-pc-windows-msvc' }}/release/steamid-replacer${{ matrix.platform == 'windows-latest' && '.exe' || '' }}
